#!/bin/bash
#		 Required    Optional
# Use: forecast  <location>  
for (( i = 0; i < ${#aWeatherFull[*]}; i++ ))
do
	eval time='$'"{aWeatherPoint"$i"[0]}"
	time=$(date -d @$time +%H)
	#echo $time
	if [ $time == 12 ] || [ $time == 13 ] || [ $time == 14 ]
	then
		for (( j=0; j<7;j++ ))
		do	
			eval var='$'"{aWeatherPoint"$i"["$j"]}"
			if [[ $j == 0 ]]
			then 
				var=$(date -d @$var '+%A %d %B %Y')
			fi
			echo -n ${weatherText[$j]}$var
		done
		echo -e "\n"
	fi
done
