#!/bin/bash
#		 Required    Optional Optional
# Use: 	weather  <location>  <units>  <timeFormat>

# Importing preferences from Prefs.cfg #
source Prefs.cfg

# First parameter after command #
location=$(echo $1 | sed 's/\-/%20/g')

# Second parameter after command #
if [[ ! -z "$2" ]]
then
	case $2 in
		"-12")
			timeFormat="12"
			;;
		"-24")
			timeFormat="24"
			;;
		"-s")
			singleEvent="y"
			;;
		"-nC")
			clearTerminal="n"
			;;
		"-i")
			units="imperial"
			;;
		"-m")
			units="metric"
	esac
fi

if [[ ! -z "$3" ]]
then
	case $3 in
		"-12")
			timeFormat="12"
			;;
		"-24")
			timeFormat="24"
			;;
		"-s")
			singleEvent="y"
			;;
		"-nC")
			clearTerminal="n"
			;;
		"-i")
			units="imperial"
			;;
		"-m")
			units="metric"
	esac
fi

if [[ ! -z "$4" ]]
then
	case $4 in
		"-12")
			timeFormat="12"
			;;
		"-24")
			timeFormat="24"
			;;
		"-s")
			singleEvent="y"
			;;
		"-nC")
			clearTerminal="n"
			;;
		"-i")
			units="imperial"
			;;
		"-m")
			units="metric"
	esac
fi

if [[ ! -z "$5" ]]
then
	case $5 in
		"-12")
			timeFormat="12"
			;;
		"-24")
			timeFormat="24"
			;;
		"-s")
			singleEvent="y"
			;;
		"-nC")
			clearTerminal="n"
			;;
		"-i")
			units="imperial"
			;;
		"-m")
			units="metric"
	esac
fi

# Operation tha clear the terminal, enabled by default, can be disabled easily using ./UpdatePrefs.sh
if [[ "$clearTerminal" == "y" ]]
then
	clear
fi
echo -e '\e[1A'

# Time format selection #
if [[ "$timeFormat" == "12" ]]
then
	timeFormat="+%I:%M:%S"
else
	timeFormat="+%H:%M:%S"
fi

# Units of measurement selection #
if [[ "$units" == "imperial" ]]
then
	unitTemp="F"
	unitWind="mph"
else
	unitTemp="C"
	unitWind="m/s"
fi

cat $installLocation'/Banner.txt'

# Main loop that display data accordingly to Prefs.cfg
while :
do
	read temp tempFeel tempMin tempMax humidity sunrise sunset < <(echo $(curl -s --request GET --url 'api.openweathermap.org/data/2.5/weather?q='$location'&appid='$apiKey'&units='$units | jq '.main.temp, .main.feels_like, .main.temp_min, .main.temp_max, .main.humidity, .sys.sunrise, .sys.sunset' ))
	
	echo "The temperature is ${temp}${unitTemp}, but it feels like ${tempFeel}${unitTemp}"
	echo "The humidity is at ${humidity}%"
	echo "Min: ${tempMin}${unitTemp} | Max: ${tempMax}${unitTemp}"
	echo -e "The sun will rise at "$(date -d @${sunrise} ${timeFormat})" and set at "$(date -d @${sunset} ${timeFormat})

	# If user choose to not update every n seconds, while loop will be broken. This feature is disabled by default, but editable using ./UpdatePrefs.sh
	if [[ "$singleEvent" == "y" ]]
	then
		break
	fi

	# Refresh data timer #
	sleep $refreshTime

	# Clear every line before updating stats #
	echo -e '\e[5A'
done
